### ISSUE TITLE
Header, Footer not in correct locations

### ISSUE THREAD

**Issue by ghost** [Eyetifacts/Pizza_ShopFE#22]
Currently, the components for the header and footer are being rendered within just the HomePage.js page render. If we render any other page we would be missing those sections. If we want them to render across all pages since they're a constant component, they should be rendered within the App.js or index.js wherever frontend routing will take place. With React we should only be rendering these components once, not every time a new page is loaded.

**Comment by Eyetifacts** [comment]
Yeah, likely we need an App page with a Header and footer.  Then routes to each of the navigating pages.  Something like that.

**Comment by Eyetifacts** [comment]
Also, created our first Jira Bug for this issue:  PSST-27.  Landmark moment !

**Comment by pratik9818** [comment]
Hi, @TheClutchC I will work  on this issue please assign this issue to me

**Comment by ghost** [comment]
I have added hash routing to the page links as well as NavLink components to each link in the navbar and the logo.

Ready to close issue after pull request is approved.
